import {  Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";



const robotoFont = Roboto({
  
  variable: "--font-Roboto",
  subsets :["latin"],
})


export const metadata = {
  title: "BookMart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${robotoFont.className} h-full antialiased`}
    >
      <body>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
